import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/block/navbar";
import { geistMono, geistSans, ikeBold } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ikeBold.variable} antialiased`}
      >
        <Navbar />
        <main className="mt-20 px-6">{children}</main>
      </body>
    </html>
  );
}
